# Generated by Django 3.1.4 on 2020-12-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addriver', '0002_auto_20201209_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='RiverName',
            field=models.CharField(max_length=25),
        ),
    ]
